export const section1 = [
  'Hi Greg',
  'Hello',
  'omg what',
  'Hi all',
  'Collab with Hasan Piker when?',
  'TRANS RIGHTS ARE HUMAN RIGHTS',
  'Hihi',
  'Greggles!',
  '🍿🍿🍿',
  'Been a while since I caught the stream hiiiii!',
  'Guys I’ve developed feelings for my trans friend am I still straight?',
  'Hi all',
  'Greg the Man!',
  'omg discount Blaire White I love your work',
  'What is this shit?',
  'Yo wtf',
  '#CancelGreg',
  'man fuck this guy',
  'Lmao traps are gay',
  'Surprise streammmmmmm',
  'Hi all',
  'Greg!',
  '???',
  'Sorry? For what?',
  'omfg he’s gonna do it',
  'Hi Greg',
  'What’s going on?',
  'my expectations are rock bottom',
  'sadge 😭greg humbled',
  'Pussy',
  'Wha',
  'Fuk dis',
  'Hi all',
  'Grow a pair hahahahaha',
  'You’ll never be a real woman',
  'tf is this bullshit',
  '2 broke 2 woke',
  'Fml',
  'Eww don’t fkn cry or shit',
  'You have nothing to apologise for! Speak your truth!',
  'Whats going on',
  'You did nothing wrong',
  'Shiiiiit',
  'Ladygreg pepega',
  'What am I missing?',
  'Ahhhh Greg!',
  'Yes boi!!!!!!!!!!!!!!!!',
  'wot',
  'Tranny POS',
  'fucking grow up ',
  'YEEEEEEEEEEESSSSSSSSSSSSSSSSSS',
  'Hahahahhahahaha',
  'Real mature.',
  '#Justiceforgreg',
  '#IStandWithGreg',
  'That’s my man',
  'lmaooooooooooooooooooooooooo',
  '💀',
  'libs get rekt',
  'Good one, Greg!',
  '💀💀💀💀💀💀💀💀💀💀',
  'Nah mate youre one of the good ones. You didn’t do anything wrong',
  'TERFs can go die in a fire',
  'Hahahahahahahahahah',
  '💀💀💀💀💀💀💀',
  'WW OHIO RIZZLER SKEET POGGERS',
  '🤣🤣🤣🤣🤣🤣',
  'Fuk yes!',
  'Bwahahahahahahaha',
  'NAURRRRRR',
  'Ahh you got me Greg',
  'Take it bitch',
  'TRANS RIGHTS',
  'KING GREG',
  'Youre a real joker mate',
  '🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️',
  'IM DA JOKA BABYYY',
  'Ur mama so ugly u needed 2 paper bags to do her',
  'Wouldn’t touch that shit',
  'Ur mama',
  'Aaaaaaaaaaaiiiight Big G!!!!!!!!!!!!!!',
  'mad laddddddddddddd',
  'GREG! GREG! GREG!',
  'BASED',
  'Go Greg!',
  'U da man',
  'Fuk em ggreg',
  'I IDENTIFY AS BASED',
  'youll never be a real man '
]

export const section2 = [
  'Amelia Fckin Collins',
  'Boooo',
  'Do you think we should be teaching kids trans acceptance in school?',
  'Dont waste ur time shes noone',
  'Hot take: you can and should be sexist to TERFs.',
  'I am so behind',
  'My dog died but this bitch lives 🙁',
  'Whos seen this? Is there a link',
  'Stoopid Bitch',
  'fAcTs AnD lOgIc',
  'She always gets so triggered and then tries to intellectualize it it\'s pathetic',
  'whomst',
  'My expectations for the IQ of Greg\'s chat were at rock bottom already and somehow it\'s even worse than I feared. You should all be ashamed of yourselves.',
  'wtf guys stop calling Greg a girl',
  'bruh stop edging get to the crashout already',
  'irrelevant',
  'Nah dw Greg does it all the time its chill',
]

export const section3 = [
  'Who does she think she is?',
  'This is why leftism has no place in universities.',
  'just make out with her already fuckin lesbians',
  '#FeminismIsCancer',
  'god shes annoying',
  'Cow',
  'Gross',
  'ugh all this drama I just wanna grill dammit',
  'new sub who dis',
  'Link pls',
  'So fugly',
  'This is ur brain on black mold',
]

export const section4 = [
  '‘Trans identity marker’ I SWEAR BY GODWIN’S LAW-',
  'Omg what a fuckin BITCH',
  'something something leopards eating faces',
  'Lol bruh ur on the internet what did you expect',
  'Ladies stooooooooooop',
  'left stop eating itself challenge impossible',
  'Shut her down!',
  'TRANS RIGHTS ARE HUMAN RIGHTS',
  'What a cow',
  'Wow this is such bullshot',
  'MOOOOOOOOOOOOOOOOOOOOOO',
  'I like my men in dresses hahahah gayboi',
]

export const section5 = [
  'I hate this chat',
  'BASED GREG',
  'Another brick in her head!',
  'TASTE.',
  'Oh mate',
  'Haha sounds like Amelia needs an education!',
  'Am I still trans if I wear socks with sandals',
  'This is why I love you Greg you always cut through the bullshit I’m so fucking grateful',
  'Speak truth brother',
  'How can she be a professor? Does she teach this stuff? Where does she work?',
  'What song',
  'Who is Pink Floyd',
  'Wow she serious',
  'Wtf',
  'Stream fornight',
]

export const section6 = [
  'am I still trans if I’m a lobster in a dominance hierarchy',
  'what is wrong with you shes like a teenager',
  'Stream fornit',
  'Greg why my eyessssss',
  'NO WAY',
  'Getting second hand dysphoria just looking at her jfc',
  'maybe if tHeY didn\'t want harassment they\'d stay off the fuckin internet',
  'FUCK TUCUTES',
  'TUCUTE DEATH CAMP WHEN',
  '😭 💀 😭💀😭💀',
  'Hows she real',
  'Not the otherkin pipeline nooooooo',
  'AAAAAAAAAAAAAAAAAA',
  'WHY',
  'ewwwwwww',
]

export const section7 = [
  'Why are you telling us this?',
  'TRANS MEN ARE MEN',
  'God I’m tearing up this is EXACTLy what happened to me they used to actually hit me too…',
  'aww boohoo you got bullied at school bitch please try getting your ass beaten every night by your dad like he probably should’ve grow tf up',
  'and then you grew up to BE the bully...pathetic',
  'Dude she’s not worth getting this triggered over',
  'Thats…not that bad bro',
  'love u Greg',
  'Trans rights blahaj gang',
  'fake and homosexual',
  'so happy youre better now greg great to see trans ppl thriving',
  'Fakenewsfakenews',
  'Hope you’re okay Greg',
  'TRANS RIGHTS ARE HUMAN RIGHTS',
  'Stram 4tnAIt',
  'Omg',
  'Oof yeah he’s gonna go for the jugular',
  'Angry Greg scares me',
  'I just got here ahs he said anything about Juinper yet?',
  '1000 yard stare',
  'T r i g g e r e d',
  'GAYYYYYYYYYYY',
  'Bro you okay? Maybe log off for the night? Respond when you’re more clearheaded?',
  'This is how Elliot Rodgers are created',
  'I don’t want to live on this planet anymore',
  'preach',
  'omg true tho',
  'God Greg I applaud you. I’d never be able to be this articulate if I was in so much pain. We’re here for you.',
  'Guys I wanna donate why can’t I donate',
  'Who even is she',
  'Ur all gullible idiots',
  'I feel like I shouldn’t be here…',
  'Righteous Greg = best Greg',
  'Fuck you Amelia this is what your bullshit leads to',
  'woah did not expect to open the stream to this goddamn',
  'Am I still trans if I shave my pubic hair but not my beard?',
  'Why bother with her tho? Tucutes are the real threat. And it’s more fun to watch you fuck with them.',
  'FUCK YOU AMELIA',
  'I LOVE MISOGYNY',
  'MY BOY',
  'TRUE',
  'GO OFF KING',
  'FEMINISM IS CANCER',
  '🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️',
  'THERE HE ISSSSSSS',
  'the G in LGBT stands for GREGGGGGG'
]

export const section8 = [
  'SO FUCKING TRUE',
  '#IHATEWOMEN',
  'omg is he serious?',
  'actual genius',
  'So you hate yourself? 🤔',
  'google how do I detransition so I don’t become a woman and Greg can still like me',
  'BOOM.',
  'GET HER ASS',
  'MIC DROP',
  'FUCKING REKT',
  'DJFAHSFHISAD',
  'YEEEEEAAAAAAHHHH BOIIIIIIIIIIII',
  'BROOOOOOO',
  'FUCK YEAH',
  'Hell yeah',
  'TRANS RIGHTS ARE HUMAN RIGHTS',
  'Cmonnnnnnn',
  'WE GETTING DEMONITIZED TONIGHT FOLKS',
  'WERK KING',
  '🦞🦞🦞🦞🦞🦞🦞',
  'true and heterosexual',
  'TRUUUUUUUUUUUUUUUUUUU',
  'KING GREG',
  'Lollllllllllllllllll',
  'Niceeeee',
  ' FUCK EM UP',
]

export const section9 = [
  'am i transphobic if my dog wears pink',
  'Greg check Juniper\'s Insta',
  'SHe probably stalked KiwiFarms for help or something',
  'Yeah that’s a low blow…I’m sorry Greg…',
  'Hes a master debaiter',
  '#ByeGreg',
  'check Juniper’s insta again',
  'LOOK AT THE NOTES POST COWARD',
  'I’m a memesogynist',
  'The truth hurts ey?',
  'I’m a woman and Amelia makes me hate my gender too lmao',
  'GREG WTF DID YOU DO TO JUNIPER',
  'greg you missed juniper\'s notes post',
  'fuck you Greg #ByeGreg',
  'Guys you had to be there the look on his face was fucking priceless thats why he wont show it now',
  'Holy shit everyone in here is awful I hate the world',
  'ITS TRANSPHOBIC TO USE MY REAL NAME REEEEEEE',
  'talk about Juniper',
  '#ByeGreg',
  'Fucking hell what a bitch',
  'Fuck you Amelia',
  'TALK ABOUT JUNIPER',
  'it IS just a name tho I don’t get it',
  'EVERYONE READ JUNIPERS PROFILE GREG IS TBE LITERAL FUCKING WORST HOW CAN YOU THINK THIS IS OKAY?!?!?!?!?',
  'Fucking hell Greg I used to respect you… #ByeGreg',
  'I wanna punch those glasses off her smug pig face fuck her',
  'LOG OFF YOU FUCKING MISOGYNIST BULLY #ByeGreg',
  'nice job ignoring juniper\'s latest post you dishonest prick #ByeGreg',
  'ADDRESS THE JUNIPER SITUATION NOW',
  'You fucking killed her piece of shit omg',
]

export const section10 = [
  'omg guys its his boyfrienddddd',
  'HI SIMON',
  'TELL SIMON WE SAID HI',
  'HI SIMON',
  '#ByeGreg',
  '#HiSimon',
  'My dad just walked by and I alt-tabbed to gay porn bc its more heterosexual than this.',
  'Hi Simon!',
  'Lolllll',
  'Simon come get your boyfriend he’s spiralling bad',
  'Hi Simon!',
  'Who tf is Simon???',
  'Wait Greg’s gay?',
  'Hi Simon!',
  '#ByeGreg',
  'What is happening',
  'this was a bad night for a weed relapse',
  'Where’d he go?',
  'What the fuck is happening',
  '#ByeGreg',
  'I’m so confused',
  '#ByeGreg',
  'oh bro wtf',
  'what',
  'what???',
  'What did he sayyyyy',
  'GREG',
  '#ByeGreg',
  'im confused',
  'Most chaotic stream of the month',
  'GREG SENPAI',
  'Straem fortniht',
  'AUTISM IS MY SUPERPOWER',
  '#ByeGreg',
  'HOLY SHIT',
  'WHAT',
  'WHAT THE FUCK',
  'What',
  'waaaaaat',
  '#ByeGreg',
]

export const section11 = [
  'OH MY GOD',
  'Prove it prove youre him',
  'whats going on',
  'LMAO',
  'Greg. Breathe. Close the stream. Get offline.',
  'omg this is the gift that keeps on giving',
  'Coleen Balinger eat your heart out',
  'Greg it\'s over',
  'GET HIS ASS SIMON',
  'GO OFF SIMON',
  'Glad you got away from this abusive asshole, Simon.',
  'The drama channels are gonna have a field day with this',
  '#ByeGreg',
  'Am I still trans if I got arrested for leaving my dog in a hot car?',
  'I am so confused rn',
  'Mom take me home Im scared',
  'plot twist: Simon is Gregs alt account',
  'fucking degenerates you should have a suicide pact together dumb fucks',
  'YOU COULDNT MAKE THIS SHIT UP',
  'fellas is it gay to indoctrinate my roommate into transitioning?',
  'This is just sad now Im so uncomfortable',
  'ENBY RIGHTS',
  'cursed',
  'this is it m8 you lost it get a real job',
  'Greg...',
  'Youre braver than the troops for putting up with this shit for so long istg',
  'I thought he said he wasn\'t gonna look at chat?',
  'SIMON! WE LOVE YOU',
  'jesus',
  'Men would rather start a youtube channel than go to therapy',
  '#ByeGreg',
  'Am i still trans if i identify as cis',
  '#ByeGreg',
  'hes losing his mcfucking mind',
  'Onision 2.0',
  '#ByeGreg',
  'GREG GET THERAPY',
  '#ByeGreg',
  'I mean…you guys did sya you like angry greg…',
  'fuck',
  'fucking hell I see so much of myself in him…',
  '40%',
  'Is this all a stunt?',
  '#ByeGreg',
  '#ByeGreg',
  'Simon is my cousin he hates Greg too',
  'Wait guys he mentioned Simon earlier right?',
  'Isn’t Simon enby?',
  '#ByeGreg',
  'Ye it’s his flatmate',
  'Whose simon?',
  'My brain hurts',
  'What the fuck',
  '#ByeGreg',
  'He said something about him moving out??',
  'This is hilarious',
  '40% live on stream (not clickbait)?!?!?!?!?!',
  '#ByeGreg',
  'You need some fucking mods',
  'guys do we know what city he lives in I’m legit worried about him',
  'not surprised his boyfriend left good for him',
  'Stream fortnitee',
  'WHY GOD WHY',
  'natural selection',
  'well this was a weird notification to wake up to',
  '#ByeGreg',
  'I am so fucking confused',
  'Who’s Juniper?',
  'Guys we should not be watching this I’m gonna leave',
  'Holy fuck what was he saying earlier about doxxes???',
  'Baaaaait',
  '#ByeGreg',
  'How are you all falling for this?',
  'Greg…mate…just take a break for a while…we love you…please…',
  'This is insane',
  'We love you Greg 🫂',
  'Am I still trans if I go fishing every Sunday to impress my daddY?',
  '#ByeGreg',
  '♥️',
  'Fuck this guy',
  'Trans rightssssss',
  'So manipulative',
  'This isn’t funny anymore',
  'Mr Chat I don’t feel so good…',
  'Aww I wanna send him a Blahaj to hug',
  '#ByeGreg',
]

export const section12 = [
  'shit',
  '♥️♥️♥️',
  'jesus',
  'Greg don’t try and be serious with these clowns',
  '#ByeGreg',
  'touch grass',
  'Look at your audience Greg - you claim to care about trans people - do you really want these people following you? You’re right: they don’t care. So maybe you need to make better content for the people who DO. The ones you hate are the ones that care the most. I hope you find your peace.',
  'mom can we go back to talking about pimples pls im scared',
  'fucking christ I did not ask to be so attacked so early in the morning',
  'I’m fucking crying Greg what are you doing to yourself',
  'Most Normal Tranny',
  'Oh honey I am so so sorry it does get better I promise',
  'WHAT IS HAPPENING CAN SOMEBODY PLEASE EXPLAIN',
  '#ByeGreg',
  '♥️♥️♥️♥️♥️',
  '40%',
  'fucking bots',
  'guys I’m a trans girl',
  '#ByeGreg',
  'I’m so fuckign uncomfortable',
  '🫂',
  'He’s not well',
  'Guys wtf',
  '#ByeGreg',
  'How drunk even is he????',
  'hi',
  'this is a fever dream',
  'I feel like I’m watching an experimental student film',
  '#ByeGreg',
  'OKAY COOL BUT YOU CAUSED A TEENAGER TO FUCKING KILL HIMSELF CAN WE GET BACK TO THAT PLEASE?????',
  '#ByeGreg',
  '🫂🫂🫂🫂',
  '#ByeGreg',
]

export const section13 = [
  'UGH',
  'Go fuck yourself',
  '#ByeGreg',
  'I fucking hate all of you',
  'why is humanity like this',
  'TRUE',
  '#ByeGreg',
  'we get it you hate yourself why are you still here',
  'We hate you too ♥️',
  '#ByeGreg',
  'if you hate yourself so much there’s one simple thing you can do…',
]

export const section14 = [
  'pogchamp',
  'die mad',
  '#ByeGreg',
  'Holy shit',
  'oh god',
  'wtf',
  'triggered…?',
  '40%',
  'HE SHOULD’VE DONE IT',
  '40%',
  '#ByeGreg',
  'What does 40% mean?',
  '40%',
  'omg no',
  'greg just fucking log off',
  'It means the new world order without fags like you in it',
  'this is',
  'Greg',
  'I’m so fuckign uncomfortable',
  '#ByeGreg',
  'turn the camera off jfc',
  '#ByeGreg',
  '🫂',
  '🫂🫂🫂🫂',
  'Greg pls don’t do anything stupid you can get through this nobody wants you dead',
  '♥️',
  'I DO',
  'Greg seek professional help',
  'Fucking hell my heart is breaking',
  'WHAT IS HAPPENING',
  'Hes fucking deranged all trannies are',
  'He’s not well',
  'Guys wtf',
  '#ByeGreg',
  'How drunk even is he????',
  'hi',
  '#ByeGreg',
  'guys I’m gonna go',
  'am I still trans if I’m fucking dead?',
]

export const inject1 = [
  {
    user: null,
    text: 'Good one Greg, nice apology'
  },
  {
    user: null,
    text: 'Tranny POS'
  },
  {
    user: null,
    text: 'Well that seemed sincere... 🙄'
  },
]

export const inject2 = [
  {
    user: null,
    text: 'TRANS EXCLUSIVE RADICAL FEMINIST'
  },
  {
    user: null,
    text: 'TERF = trans excl. radical feminist'
  },
  {
    user: null,
    text: 'a massive piece of shit?'
  },
]

export const inject3 = [
  {
    user: null,
    text: 'Why d\'you bother with the people on our side, Greg? Keep dunking on the leftist SNOWFLAKES'
  },
]

export const inject4 = [
  {
    user: null,
    text: 'whoah'
  },
  {
    user: null,
    text: 'Calm down greg'
  },
  {
    user: null,
    text: 'LOL TRIGGERED!!!'
  },
  {
    user: null,
    text: 'triggered much?'
  },
]

export const inject5 = [
  {
    user: null,
    text: 'what happened to Juniper?'
  },
  {
    user: null,
    text: 'Omg Greg check their insta now!'
  },
  {
    user: null,
    text: 'jeez... juniper\'s IG account... '
  },
]

export const inject6 = [
  {
    user: 'evyves',
    text: 'Hey Chat, I\'m the afformentioned House mate. Didnt expect Greg to get my message while he was still streaming but oh well. As I\'m sure you can all tell, his toxic behaviour has gotten him into some hot water. Not sure he\'s got himself out yet given how this stream is going. Anyway, be kind and look after yourselves.'
  },
]

export const inject7 = [
  {
    user: 'comrade',
    text: '"Comrade" here. Ev has logged off mate. You\'ve fucked it'
  },
]

export default {}
