export const tweet = [
  {
    user: 'amelia',
    time: '1:49 PM',
    date: 'Aug 17, 2025',
    content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
    views: '1.8M',
    comments: '1.8k',
    retweets: '3.1k',
    likes: '74k',
    saves: '1.2k'
  },
  {
    user: 'jk',
    time: '11:17 PM',
    date: 'Jun 21, 2023',
    content: "'Cis' is ideological language, signifying belief in the unfalsifiable concept of gender identity. You have a perfect right to believe in unprovable essences that may or may not match the sexed body, but the rest of us have a right to disagree, and to refuse to adopt your jargon.",
    views: '21M',
    comments: '10k',
    retweets: '40k',
    likes: '196k',
    saves: '5.2k'
  },
]

export const tweetStorm = [
  [
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
  ],
  [
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
  ]
]