export const tweet = {
  amelia: {
    user: 'amelia',
    time: '1:49 PM',
    date: 'Aug 17, 2025',
    content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
    views: '1.8M',
    comments: '1.8k',
    retweets: '3.1k',
    likes: '74k',
    saves: '1.2k'
  },
  jk: {
    user: 'jk',
    time: '11:17 PM',
    date: 'Jun 21, 2023',
    content: "'Cis' is ideological language, signifying belief in the unfalsifiable concept of gender identity. You have a perfect right to believe in unprovable essences that may or may not match the sexed body, but the rest of us have a right to disagree, and to refuse to adopt your jargon.",
    views: '21M',
    comments: '10k',
    retweets: '40k',
    likes: '196k',
    saves: '5.2k'
  },
}

export const tweetStorm = {
  amelia: [
    tweet.amelia,
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
  ],
  jk: [
    tweet.jk,
    {
      user: 'jk',
      time: '8:27 PM',
      date: 'Feb 6, 2025',
      content: "Congratulations to every single person on the left who’s been campaigning to destroy women’s and girls’ rights. Without you, there’d be no images like this.",
      image: 'src/assets/tweet-images/GjGCOzdWcAAIRA5.jpeg',
      views: '40.3M',
      comments: '18k',
      retweets: '93k',
      likes: '730k',
      saves: '22k'
    },
    {
      user: 'jk',
      time: '4:40 AM',
      date: 'Sep 25, 2024',
      content: "I get the same royalties whether you read them or burn them. Enjoy your marshmallows! 😘",
      image: 'src/assets/tweet-images/GYQx9VVWEAANois.jpeg',
      views: '24M',
      comments: '23k',
      retweets: '38k',
      likes: '540k',
      saves: '6.5k'
    },
    {
      user: 'jk',
      time: '4:40 AM',
      date: 'May 12, 2024',
      content: "I didn’t compare him to one. He IS one.",
      image: 'src/assets/tweet-images/dailymail.png',
      views: '29M',
      comments: '12k',
      retweets: '47k',
      likes: '404k',
      saves: '10k'
    },
    {
      user: 'jk',
      time: '12:59 AM',
      date: 'Oct 18, 2023',
      content: "No.",
      image: 'src/assets/tweet-images/F8pYgyLbYAAw9Xs.jpeg',
      views: '47M',
      comments: '28K',
      retweets: '66K',
      likes: '383K',
      saves: '7k'
    },
    {
      user: 'jk',
      time: '6:26 AM',
      date: 'Feb 28, 2025',
      content: "Explain what makes them trans.",
      image: 'src/assets/tweet-images/thomaswillet.png',
      views: '37.9M',
      comments: '5.7K',
      retweets: '25K',
      likes: '330K',
      saves: '11k'
    },
    {
      user: 'jk',
      time: '10:39 PM',
      date: 'Jan 25, 2023',
      content: "Men defining what a woman is, what women should and shouldn’t fear, what women should and shouldn’t say, what rights women should be fine with giving up and, of course, what constitutes ‘real’ misogyny: get a bloody mirror. That’s real misogyny, looking right back at you.",
      views: '30M',
      comments: '16K',
      retweets: '51K',
      likes: '272K',
      saves: '4.5K'
    },
    {
      user: 'jk',
      time: '6:21 AM',
      date: 'Dec 29, 2024',
      content: "There are no trans kids. No child is 'born in the wrong body'. There are only adults like you, prepared to sacrifice the health of minors to bolster your belief in an ideology that will end up wreaking more harm than lobotomies and false memory syndrome combined.",
      image: 'src/assets/tweet-images/Gf6JqBcWwAABuk-.jpeg',
      views: '11.8M',
      comments: '8.3K',
      retweets: '30K',
      likes: '233K',
      saves: '6.1K'
    },
    {
      user: 'jk',
      time: '8:02 AM',
      date: 'Jun 7, 2020',
      content: "If sex isn’t real, there’s no same-sex attraction. If sex isn’t real, the lived reality of women globally is erased. I know and love trans people, but erasing the concept of sex removes the ability of many to meaningfully discuss their lives. It isn’t hate to speak the truth.",
      views: '',
      comments: '32K',
      retweets: '87K',
      likes: '212K',
      saves: '7.6K'
    },
    {
      user: 'jk',
      time: '10:58 PM',
      date: 'May 12, 2024',
      content: "Calling a man a man is not 'bullying' or 'punching down.' Crossdressing straight men are currently one of the most pandered-to demographics in existence, and women are under no obligation to applaud the people caricaturing us.",
      views: '8.3M',
      comments: '4.4K',
      retweets: '27K',
      likes: '195K',
      saves: '3.8K'
    },
    {
      user: 'jk',
      time: '10:52 AM',
      date: 'Nov 22, 2024',
      content: "If a man is a woman, there's no such thing as a woman. You're desperate to be categorised as female, but by entering the category, you destroy it. You know that, which must suck for you, but not as much as it sucks for the women & girls fighting to retain their rights and spaces.",
      image: 'src/assets/tweet-images/Gc8lyRBXcAAA3rD.jpeg',
      views: '7.9M',
      comments: '6.5K',
      retweets: '23K',
      likes: '187K',
      saves: '4.7K'
    },
    {
      user: 'jk',
      time: '9:01 PM',
      date: 'Jun 24, 2025',
      content: "Attention all men telling me I look like a trans woman: I’m sensing that this isn’t meant as a compliment. In fact, the implication seems to be that trans women look male, or odd, or ugly. This is appallingly transphobic and I’ll thank you to take your bigotry off my timeline.",
      views: '6M',
      comments: '8.9K',
      retweets: '13K',
      likes: '189K',
      saves: '3.1K'
    },
    {
      user: 'jk',
      time: '8:54 AM',
      date: 'Oct 24, 2024',
      content: "'We must not publish a study that says we're harming children because people who say we're harming children will use the study as evidence that we're harming children, which might make it difficult for us to continue harming children.'",
      image: 'src/assets/tweet-images/Gamz2mAXgAA40Km.jpeg',
      views: '27.9M',
      comments: '3.6K',
      retweets: '51K',
      likes: '173K',
      saves: '12K'
    },
    {
      user: 'jk',
      time: '2:27 AM',
      date: 'Jul 18, 2024',
      content: "Amazed this still needs saying, but some don't seem to have got the memo. If calling me 'transphobe' and 'fascist' was going to scare me out of speaking up for women's rights, it would have happened years ago. Whatever the square root of not giving a fuck is, that's where I am.",
      views: '7.4M',
      comments: '5K',
      retweets: '16K',
      likes: '164K',
      saves: '2.2K'
    },
    {
      user: 'jk',
      time: '2:32 AM',
      date: 'Jun 30, 2025',
      content: "When you tell a woman she must pretend a man is a woman, you’re asserting the right to control her speech and perception of reality, while also trivialising and devaluing her female-specific experience. You’re asking her to agree that ‘woman’ is a concept men can embody at will.",
      image: 'src/assets/tweet-images/benjaminryan.png',
      views: '11.1M',
      comments: '4.5K',
      retweets: '24K',
      likes: '165K',
      saves: '8.3K'
    },
    {
      user: 'jk',
      time: '10:52 PM',
      date: 'Aug 7, 2024',
      content: "For the record, bombarding me with pictures of athletic women to ‘teach’ me that women don’t all look like Barbie is like spamming me with pics of differently-shaped potatoes to prove rocks are edible. I can still see the difference and you look frankly bonkers.",
      views: '5.3M',
      comments: '7.6K',
      retweets: '14K',
      likes: '155K',
      saves: '2.1K'
    }
  ],
  ameliaVsGreg: [
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'amelia',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
    {
      user: 'greg',
      time: '1:49 PM',
      date: 'Aug 17, 2025',
      content: "Lorem ipsum dolor sit amet phasellus duis aenean. Quisque lacus mattis in urna sagittis gravida mattis venenatis. Eros hendrerit congue dolore tempor eleifend donec integer urna morbi sed quam. Hendrerit nisi interdum cursus eu posuere nulla blandit ac. Aliquam phasellus iaculis aliquet et etiam purus consequat cras urna.",
      views: '1.8M',
      comments: '1.8k',
      retweets: '3.1k',
      likes: '74k',
      saves: '1.2k'
    },
  ]
}