export const section1 = [
  'Hi Greg',
  'Hello',
  'Hi Greg',
  'Hey Greg',
  'Greg!',
  'Hi all',
  'Collab with Destiny when?',
  'Hihi',
  'Greggles!',
  'Been a while since I caught the stream hiiiii!',
  'Yo G!',
  'Hey Greg',
  'Hi Greg',
  'Sup bro',
  'GREG!!!!!',
  'Hi',
  'Hi',
  'ITSGREGG!!!!!!!',
  'Hey',
  'Sup',
  'Guys I’ve developed feelings for my trans friend am I still straight?',
  'Hi all',
  'Greg the Man!',
  'omg discount Blaire White I love your work',
  'What is this shit?',
  'Yo wtf',
  'Lmao traps are gay',
  'Surprise streammmmmmm',
  'Hi all',
  'Greg!',
  '???',
  'Sorry? For what?',
  'omfg he’s gonna do it',
  'Hi Greg',
  'What’s going on?',
  'Wachu talkin bout',
  '?',
  'Hi all',
  'Woah what did I miss?',
  'Hi Greg',
  'bruh',
  'Huh?',
  '???',
  'sadge 😭greg humbled',
  'Pussy',
  'Wha',
  'Fuk dis',
  'Hi all',
  'Grow a pair hahahahaha',
  'You’ll never be a real woman',
  'tf is this bullshit',
  '2 broke 2 woke',
  'Fml',
  'Eww don’t fkn cry or shit',
  'You have nothing to apologise for! Speak your truth!',
  'Whats going on',
  'You did nothing wrong',
  'Shiiiiit',
  'Ladygreg pepega',
  'What am I missing?',
  'Ahhhh Greg!',
  'Yes boi!!!!!!!!!!!!!!!!',
  'wot',
  'fucking grow up ',
  'YEEEEEEEEEEESSSSSSSSSSSSSSSSSS',
  'Hahahahhahahaha',
  '#Justiceforgreg',
  '#IStandWithGreg',
  'That’s my man',
  'lmaooooooooooooooooooooooooo',
  '💀',
  'libs get rekt',
  '💀💀💀💀💀💀💀💀💀💀',
  'Nah mate youre one of the good ones. You didn’t do anything wrong',
  'Hahahahahahahahahah',
  '💀💀💀💀💀💀💀',
  'WW OHIO RIZZLER SKEET SKEET POGGERS',
  '🤣🤣🤣🤣🤣🤣',
  'Fuk yes!',
  'Bwahahahahahahaha',
  'NAURRRRRR',
  'Ahh you got me Greg',
  'Take it bitch',
  'KING GREG',
  'Youre a real joker mate',
  'Yeah! Fuk her hard bro',
  'IM DA JOKA BABYYY',
  'Ur mama so ugly u needed 2 paper bags to do her',
  'Wouldn’t touch that shit',
  'Ur mama',
  'Aaaaaaaaaaaiiiight Big G!!!!!!!!!!!!!!',
  'mad laddddddddddddd',
  '#CANCELGREG',
  '#cangelGreg',
  '#CANCELGREG #TRAPTHETRAP',
  'Cancel greg!',
  '#CANCELGREGINA',
  'my pronouns are cancel/greg',
  '#TRAPTHETRAP #cancelgreg',
  '#cancelgreg',
  '#trapthetrap',
  '#TRAPTHETAP #CANCELGREG',
  '#Justice4Greg',
  '#trapthetrap',
  '#trapthetrap',
  'NOT TRAPTHETRAP',
  'GREG! GREG! GREG!',
  'BASED',
  'Thoughts on lia thomas debate?',
  'Go Greg!',
  'U da man',
  'Fuk em ggreg',
  'I IDENTIFY AS BASED',
  'youll never be a real man'
]

export const section2 = [
  'NOT TRAPTHETRAP',
  'GREG! GREG! GREG!',
  'BASED',
  'Thoughts on lia thomas debate?',
  'Go Greg!',
  'U da man',
  'Fuk em ggreg',
  'I IDENTIFY AS BASED',
  'youll never be a real man',
  '#trapthetrap',
  '#TRAPTHETAP #CANCELGREG',
  '#Justice4Greg',
  '#trapthetrap',
  '#trapthetrap',
  'God creahted man and woman 2 be fruitful and multiply this gender cult is Satnas work',
  'GREG! GREG! GREG!',
  'Go Greg!',
  'U da man',
  'My name is greg too lol based',
  'Fuk em ggreg',
  'GO OFF DEBATE DADDYKING',
  'I identify as the king of france if you don’t call me your majesty i’ll chop your head off',
  'Amelia Fckin Collins',
  'Boooo',
  'Do you think we should be teaching kids trans acceptance in school?',
  'Dont waste ur time shes noon',
  '🙏JBP map my meanings daddy',
  'Bitch',
  'Whos seen this? Is there a link',
  'Stoopid Bitch',
  'fAcTs AnD lOgIc',
  'whomst',
  'irrelevant',
  'Cow',
  'Gross',
  'new sub who dis',
  'Link pls',
  'So fugly',
  'No one would want to fuk her',
  'girls girls ur both pretty',
  'lmaoooo good one',
  'What did she say?',
  'Pommy bitch',
  'I wanna watch this',
  'Booooooooooooooooooooooo',
  'Anyone found the clip? Share Greg!',
  'metal illness',
  'Boooooooooooooooooooooooooooooooooo',
  'What a c*nt',
  '*mental',
  'Eww gross',
  'Hahahahahahahaha',
  'HAAAAAAAHAHAHAHAHAHAAAAAAA',
  'Get em Greg!',
  'Greg identifying as the winner of the debate lol',
  'Thank god you’re not subjecting us to that shrill ass voice',
  'Who does she think she is?',
  'Keep em in the kitchen ammirite fckin feminists',
  'Lock em in the kitchem',
  'Make me a sandwich bitcgh',
  'just make out with her already fuckin lesbians',
  '#FeminismIsCancer',
  'god shes annoying',
  'This is why leftists should be banned from universities',
  'FUCK TERFS',
  'Shaddya face bitch!!!!!!!!!!!!!',
  'Harry Potter sux',
  'Grab my wand Ron hahahahaha',
  'My dog died but this bitch lives 🙁',
  'This is ur brain on black mold',
  'Greg got no wand tho',
  'Hahahahahaha',
  'Expel it from my arse!!!!!',
  'Fuk boomers',
  'stream fornite',
  'Ok boomers',
  'OK Boomers',
  'Okboomers',
  'wtf guys stop calling him a girl',
  'Boomers',
  'Boom boom boom',
  'nah man its cool he does it to himself just bants',
  'Fuk u boomers!!!!!!!!!!!!'
]

export const section3 = [
  'FUCK TERFS',
  'Shaddya face bitch!!!!!!!!!!!!!',
  'Harry Potter sux',
  'Grab my wand Ron hahahahaha',
  'My dog died but this bitch lives 🙁',
  'This is ur brain on black mold',
  'Greg got no wand tho',
  'Hahahahahaha',
  'Expel it from my arse!!!!!',
  'Fuk boomers',
  'stream fornite',
  'Ok boomers',
  'OK Boomers',
  'Okboomers',
  'wtf guys stop calling him a girl',
  'Boomers',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'nah man its cool he does it to himself just bants',
  'Ok boomers',
  'AUTISTIC SCREAMING NOISES POGCHAMP',
  'OK Boomers',
  'Okboomers',
  'You’re both fucking insufferable',
  'Boomers',
  'Is she wrong tho',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'Boomer cunt',
  'Omg what a fuckin BITCH',
  'something something leopards eating faces',
  'Lol bruh ur on the internet what did you expect',
  'Ladies stooooooooooop',
  'left stop eating itself challenge impossible'
]

export const section4 = [
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'Boomer cunt',
  'Omg what a fuckin BITCH',
  'something something leopards eating faces',
  'Lol bruh ur on the internet what did you expect',
  'Ladies stooooooooooop',
  'left stop eating itself challenge impossible',
  'Shut her down!',
  'Ugly as fuk',
  'What a cow',
  '‘Trans identity marker’ I SWEAR BY GODWIN’S LAW-',
  'Wow this is such buulshit',
  'MOOOOOOOOOOOOOOOOOOOOOO',
  'would still bang tbh',
  'I like my men in dresses hahahah gayboi',
  'I hate this chat',
  'Wow she serious',
  'Wtf',
  'Stream fornight',
  'Whois this bitch?',
  'How can she be a professor? Does she teach this stuff?',
  'Am I still trans if I wear socks with sandals',
  'TASTE.',
  'Who is this?',
  'What song',
  'Roger Waters baby!!!',
  'WE DON’T NEED NO EDUCATION',
  'Hahah sounds like Amelia needs an education',
  'This is why I love you Greg you always cut through the bullshit I’m so fucking grateful',
  'BASED GREG',
  'Another brick in her head!',
  'Oh mate',
  'Speak truth brother',
  'What song',
  'Who is Pink Floyd',
  'Wow Greg',
  'Fuk bro',
  'Were here for you Greg',
  'Greg!!!!',
  'Greg4life',
  'Hahah ya work on the voice bro',
  'Lmaoooooooooooo wat',
  'Wouldn’t be able to tell from the voice tbh shame about the rest of you',
  'You sound nasal as fuck',
  'fake and gay ✨ same tho ✨',
  'TRANNY VOICE',
  'skibidi',
  'WE CAN ALWAYS TELL'
]

export const section5 = [
  'sucks bro',
  'God made you this way',
  'mental illness',
  'God wants me to fucking kill myself then',
  'y’all need jesus',
  'He’s not trapping anyone let’s be real',
  'Well at least he’s honest',
  'Jesus was trans he identifies as bread sometimes',
  'I iDeNtIfY aS mAnLy',
  'The real OGs remember Simon!',
  'lmaooooooo',
  'getting parasocial up in this bitch',
  'Gayyyyyyyyyy',
  'I wanna bang him and I’ve never met him lmao',
  'am I trans if I got booted off my minecraft server for griefing?',
  'Oof',
  'who????',
  'So true',
  'theres no nonbinary in the dsm its not mental illness its attention seeking fuck em',
  'Yeah seen this happen to my friends too its so sad',
  'POGCHAMP',
  'My dad walked in the room and I had to alt tab to gay porn because it’s more heterosexual than this',
  'admit u wanna fuck him greg',
  'you always say the same old shit',
  'am I still trans if I’m a lobster in a dominance hierarchy',
  'bc nobodys listening',
  'aaaaaaaaaaaaa',
  'JUNIPER JUMPSCARE',
  'NOOOOOOOOOOOOOOOOOO',
  'Stream fornit',
  'Greg why my eyessssss',
  'NO WAY',
  'FUCK TUCUTES',
  '😭 💀 😭💀😭💀',
  'Greg where superchats GREG',
  'Hows she real',
  'Not the otherkin pipeline nooooooo',
  'AAAAAAAAAAAAAAAAAA',
  'WHY',
  'ewwwwwww',
  'Getting second hand dysphoria just looking at her jfc',
  'wait how old is she?',
  'TUCUTE DEATH CAMP WHEN',
  'You’re so right Greg. People like Juniper make us look like mentally ill freaks. They’ve ruined everything the trans movement stands for and now look where we are. No wonder people like Amelia fucking hate us',
  'She’s soooooo fake',
  'MAKE IT MAKE SENSE',
  'Lmao',
  'Lol nice',
  'Lolllll',
  'Hehe',
  'Thats what she said'
]

export const section6 = [
  'Greg where superchats GREG',
  'Hows she real',
  'Not the otherkin pipeline nooooooo',
  'AAAAAAAAAAAAAAAAAA',
  'WHY',
  'ewwwwwww',
  'Getting second hand dysphoria just looking at her jfc',
  'wait how old is she?',
  'TUCUTE DEATH CAMP WHEN',
  'You’re so right Greg. People like Juniper make us look like mentally ill freaks. They’ve ruined everything the trans movement stands for and now look where we are. No wonder people like Amelia fucking hate us',
  'She’s soooooo fake',
  'MAKE IT MAKE SENSE',
  'Lmao',
  'Lol nice',
  'Lolllll',
  'Hehe',
  'Thats what she said',
  'FUCK ME IN THE ASS WITH ET AL',
  'Omg he triggered her so bad it’s not even funny',
  'Fax and logitech',
  'Honestly tysm for that list it’s helped me so much talking with my parents and getting them to take me seriously ♥️',
  'PEG ME WITH YUOR EASYBIB DADDY GREG',
  'Loll okay boomer',
  'Okay Amelia',
  'Booooooomerrrrrrrrr',
  'Skibidi cum all over her face',
  'The biggest bullies will be the first to cry bully',
  '🙄',
  'TERFs always playing the victim',
  'okay but like some people deserve to be bullied tbh',
  'GODWINS LAW',
  'Omg he really said facts > feelings',
  'Based',
  'Am I still trans if im 1900 elo in chess???'
]

export const section7 = [
  'didn’t think I’d hear fascism discourse at 3am but I’m not complaining',
  'oh shit what',
  'woah',
  'omg angry greg',
  'oof',
  'triggered???',
  'wow',
  'too real bro',
  'gpoddamn',
  'pussy',
  'you are a dyke tho',
  'were they wrong???',
  'SNOWFLAKE',
  'aww bro…🫂',
  'god hes so annoying',
  'You’re a strong man Greg never forget that ♥️',
  'check your privilege snowflake',
  'aww boohoo you got bullied at school bitch please try getting your ass beaten every night by your dad like he probably should’ve grow tf up',
  'Thats…not that bad bro',
  'fake and homosexual',
  'Fakenewsfakenews',
  'Angry Greg scares me',
  '1000 yard stare',
  'T r i g g e r e d',
  'GAYYYYYYYYYYY',
  'Bro you okay? Maybe log off for the night? Respond when you’re more clearheaded?',
  'This is how Elliot Rodgers are created',
  'preach',
  'omg true tho',
  'TRUE',
  'GO OFF KING',
  'FEMINISM IS CANCER',
  'THERE HE ISSSSSSS',
  'MY BOY',
  'true and heterosexual',
  'TRUUUUUUUUUUUUUUUUUUU',
  'KING GREG',
  'Lollllllllllllllllll',
  'Niceeeee',
  'WOP WOP WOP WOP WOP GREG FUCK EM UP',
  'SO FUCKING TRUE',
  'pissing and shitting rn omg',
]

export const section8 = [
  'MY BOY',
  'true and heterosexual',
  'TRUUUUUUUUUUUUUUUUUUU',
  'KING GREG',
  'Lollllllllllllllllll',
  'Niceeeee',
  'WOP WOP WOP WOP WOP GREG FUCK EM UP',
  'SO FUCKING TRUE',
  'pissing and shitting rn omg',
  'FUCK YOU AMELIA FUCK YOU JUNIPER FUCK YOU ALL FUCK THIS FUCK MY LIFE I WANNA DIE',
  'FUCK YOU AMELIA',
  'STUPID BITCH FUCK YOU',
  'Scream fornit',
  '#IHATEWOMEN',
  'So you hate yourself? 🤔',
  'omg is he serious?',
  'actual genius',
  'B8',
  'google how do I detransition so I don’t become a woman and Greg can still like me',
  'Thoughts on Trump?',
  'bitches aint shit but hoes and tricks',
  'obvious bait try harder',
  'GO. THE FUCK. OFF!!!!!!!',
  'People are gonna clip this outta context for sure',
  'Bait',
  'gay',
  'FEMALES ARE ANIMALS',
  'am i transphobic if my dog wears pink',
  'incelcore',
  'He’s a master baiter',
  'Honestly just let her write her silly little books why even have her on why even respond this is all pointless it’ll just blow over you have bigger fish to fry tbh',
  'I’m a memesogynist',
  'I’m a woman and Amelia makes me hate my gender too lmao',
  'She’s irrelevant tho',
  'Baaaaaaaaased',
  'Omg imagine taking him seriously lmao you’re palying into his hands idiots',
  'Why bother with her tho? Tucutes are the real threat. And it’s more fun to watch you fuck with them.',
  'Hey Greg. Long time watcher, first time catching it live - just wanted to say I’ve been watching your content for years and it always brings a smile to my face. Keep being you Dude! Never Change!',
  'AM I STILL TRANS IF I DIE (REAL) (NOT FAKE) (COPS CALLED) (STEPSISTER?!?!)',
  'It’s so cool to see someone sticking up for us, someone who actually gives a shit.',
  'TRANS RIGHTS'
]

export const section9 = [
  'am i transphobic if my dog wears pink',
  'incelcore',
  'He’s a master baiter',
  'Honestly just let her write her silly little books why even have her on why even respond this is all pointless it’ll just blow over you have bigger fish to fry tbh',
  'I’m a memesogynist',
  'I’m a woman and Amelia makes me hate my gender too lmao',
  'She’s irrelevant tho',
  'Baaaaaaaaased',
  'Omg imagine taking him seriously lmao you’re palying into his hands idiots',
  'Why bother with her tho? Tucutes are the real threat. And it’s more fun to watch you fuck with them.',
  'Hey Greg. Long time watcher, first time catching it live - just wanted to say I’ve been watching your content for years and it always brings a smile to my face. Keep being you Dude! Never Change!',
  'AM I STILL TRANS IF I DIE (REAL) (NOT FAKE) (COPS CALLED) (STEPSISTER?!?!)',
  'It’s so cool to see someone sticking up for us, someone who actually gives a shit.',
  'TRANS RIGHTS',
  'Eww what',
  'Omg Greg mad lad',
  'fucking wild',
  'degeneracy',
  'pepelul',
  'worst analogy ever'
]

export const section10 = [
  'Omg imagine taking him seriously lmao you’re palying into his hands idiots',
  'Why bother with her tho? Tucutes are the real threat. And it’s more fun to watch you fuck with them.',
  'Hey Greg. Long time watcher, first time catching it live - just wanted to say I’ve been watching your content for years and it always brings a smile to my face. Keep being you Dude! Never Change!',
  'AM I STILL TRANS IF I DIE (REAL) (NOT FAKE) (COPS CALLED) (STEPSISTER?!?!)',
  'It’s so cool to see someone sticking up for us, someone who actually gives a shit.',
  'TRANS RIGHTS',
  'Eww what',
  'Omg Greg mad lad',
  'fucking wild',
  'degeneracy',
  'pepelul',
  'worst analogy ever',
  'can’t debunk your arguments if youre too busy throwing up lol genius',
  '…based?',
  'Weirdly based',
  'Not your best but I get it',
  'TRUE',
  'Oh thank god its not just me lmao',
  'Hes got a point tho',
  'GUYS THIS IS WHY YOU HAVE TO FUCKING LISTEN TO THE ARGUMENTS DONT YOU SEE THIS IS WHAT HES BEEN SAYING ALL ALONG LISTEN EVEN THO ITS DIFFICULT',
  'give it 5 mins hes gonna reveal his porn stash',
  'FUCK TERFS AND TUCUTES AND TRANSPHOBES',
  'lol yeah hentai reveal when',
  'the G in LGBT stands for GREGGGGGGG',
  'BOOM.',
  'GET HER ASS',
  'MIC DROP',
  'FUCKING REKT',
  'WE GETTING DEMONITIZED TONIGHT FOLKS',
  'DJFAHSFHISAD',
  'YEEEEEAAAAAAHHHH BOIIIIIIIIIIII',
  'BROOOOOOO',
  'FUCK YEAH',
  'Hell yeah',
  'Cmonnnnnnn',
  'WERK KING',
  '🦞🦞🦞🦞🦞🦞🦞',
  'You should be on Joe Rogan',
  'BASED KING',
  'Nah bro u good',
  'Gay',
  'We’ll let you off just this once lol',
  'Keep tellin gyourself that',
  'projectionnnnnnnnnn',
  'Hope you’re okay Greg',
  'Guys how fucking drunk is he',
  'joined late wtf is happening',
  'look at the bottle',
  'this is a clusterfuck',
  'idk hes been drinking since the start and maybe before that',
  'POGCHAMP',
  'What time is it there???',
  'Oh fuck this bit',
  'Ameliaaaaaaaa Go die in a fire bitcccccchhhhhh',
  'LMAO WHAT',
  'COWARD',
  'Holy fuck what a bitch',
  'OOF',
  'REKT',
  'Oh no',
  'SAY THE NAME',
  'SAY IT PUSSY',
  'Ohhhhhhhhh shit',
  'Guys you had to be there the look on his face was fucking priceless thats why he wont show it now',
  'Holy shit everyone in here is awful I hate the world',
  'ITS TRANSPHOBIC TO USE MY REAL NAME REEEEEEE',
  'You’ll get used to it m8',
  'Fucking hell what a bitch',
  'Fuck you Amelia',
  'Yeah that’s a low blow…I’m sorry Greg…',
  'True.',
  'SHe probably stalked KiwiFarms for help or something',
  'it IS just a name tho I don’t get it',
  'I wanna punch those glasses off her smug pig face fuck her',
  'That’s rough dude',
  'dude are you even fucking listening',
  'You look like a lesbian fucked a water buffalo and then that baby grew up to be a LoL player.',
  'TRANS RIGHTS ARE HUMAN RIGHTS',
  'nah too busy doing ur mom',
  'Makes sense',
  '40%',
  'both of you get back in the kitchen',
  'God she’s such a bitch I might have to step away',
  'This is a trainwreck I can’t look away',
  'Love you Greg',
  'wat is even happening rn',
  'Greg 🫂',
  'He’s so fucking articulate I’m in awe',
  'Strem frntige',
  'actual mental illness',
  'He’s been through so much shit omg',
  'this is history',
  'FAKE AND GAY POGCHAMP',
  'fucking mood',
  'yeah lifes a bitch it sucks so hard',
  'Fuck guys I think I’m trans is this what I have to look forward to?',
  'Psychopath behaviour how are you all falling for these crocodile tears',
  'Oh you poor sweet boy',
  'GAY',
  'This is fucking pathetic',
  'woah okay',
  'wow',
  'That’s it? That’s ALL you said?',
  'Jesus was trans he identifies as bread sometimes',
  'I iDeNtIfY aS mAnLy',
  'The real OGs remember Simon!',
  'lmaooooooo',
  'getting parasocial up in this bitch',
  'Gayyyyyyyyyy',
  'I wanna bang him and I’ve never met him lmao',
  'am I trans if I got booted off my minecraft server for griefing?',
  'Oof',
  'who????',
  'So true',
  'theres no nonbinary in the dsm its not mental illness its attention seeking fuck em',
  'Yeah seen this happen to my friends too its so sad',
  'POGCHAMP',
  'My dad walked in the room and I had to alt tab to gay porn because it’s more heterosexual than this',
  'admit u wanna fuck him greg',
  'you always say the same old shit',
  'am I still trans if I’m a lobster in a dominance hierarchy',
  'bc nobodys listening',
  'aaaaaaaaaaaaa',
  'JUNIPER JUMPSCARE',
  'NOOOOOOOOOOOOOOOOOO',
  'Stream fornit',
  'Greg why my eyessssss',
  'NO WAY',
  'FUCK TUCUTES',
  '😭 💀 😭💀😭💀',
  'Greg where superchats GREG',
  'Hows she real',
  'Not the otherkin pipeline nooooooo',
  'AAAAAAAAAAAAAAAAAA',
  'WHY',
  'ewwwwwww',
  'Getting second hand dysphoria just looking at her jfc',
  'wait how old is she?',
  'TUCUTE DEATH CAMP WHEN',
  'Boomers',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'nah man its cool he does it to himself just bants',
  'Ok boomers',
  'AUTISTIC SCREAMING NOISES POGCHAMP',
  'OK Boomers',
  'Okboomers',
  'You’re both fucking insufferable',
  'Boomers',
  'Is she wrong tho',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'Boomer cunt',
  'Omg what a fuckin BITCH',
  'something something leopards eating faces',
  'Lol bruh ur on the internet what did you expect',
  'Ladies stooooooooooop',
  'left stop eating itself challenge impossible',
  'GO. THE FUCK. OFF!!!!!!!',
  'People are gonna clip this outta context for sure',
  'Bait',
  'gay',
  'FEMALES ARE ANIMALS',
  'am i transphobic if my dog wears pink',
  'incelcore',
  'He’s a master baiter',
  'Honestly just let her write her silly little books why even have her on why even respond this is all pointless it’ll just blow over you have bigger fish to fry tbh',
  'I’m a memesogynist',
  'I’m a woman and Amelia makes me hate my gender too lmao',
  'She’s irrelevant tho',
  'Baaaaaaaaased',
  'Omg imagine taking him seriously lmao you’re palying into his hands idiots',
  'Why bother with her tho? Tucutes are the real threat. And it’s more fun to watch you fuck with them.',
  'Hey Greg. Long time watcher, first time catching it live - just wanted to say I’ve been watching your content for years and it always brings a smile to my face. Keep being you Dude! Never Change!',
  'AM I STILL TRANS IF I DIE (REAL) (NOT FAKE) (COPS CALLED) (STEPSISTER?!?!)',
  'It’s so cool to see someone sticking up for us, someone who actually gives a shit.',
  'TRANS RIGHTS'
]
export default {}
