export const section1 = [
  'Hi Greg',
  'Hello',
  'Hi Greg',
  'Hey Greg',
  'Greg!',
  'Hi all',
  'Collab with Destiny when?',
  'Hihi',
  'Greggles!',
  'Been a while since I caught the stream hiiiii!',
  'Yo G!',
  'Hey Greg',
  'Hi Greg',
  'Sup bro',
  'GREG!!!!!',
  'Hi',
  'Hi',
  'ITSGREGG!!!!!!!',
  'Hey',
  'Sup',
  'Guys I’ve developed feelings for my trans friend am I still straight?',
  'Hi all',
  'Greg the Man!',
  'omg discount Blaire White I love your work',
  'What is this shit?',
  'Yo wtf',
  'Lmao traps are gay',
  'Surprise streammmmmmm',
  'Hi all',
  'Greg!',
  '???',
  'Sorry? For what?',
  'omfg he’s gonna do it',
  'Hi Greg',
  'What’s going on?',
  'Wachu talkin bout',
  '?',
  'Hi all',
  'Woah what did I miss?',
  'Hi Greg',
  'bruh',
  'Huh?',
  '???',
  'sadge 😭greg humbled',
  'Pussy',
  'Wha',
  'Fuk dis',
  'Hi all',
  'Grow a pair hahahahaha',
  'You’ll never be a real woman',
  'tf is this bullshit',
  '2 broke 2 woke',
  'Fml',
  'Eww don’t fkn cry or shit',
  'You have nothing to apologise for! Speak your truth!',
  'Whats going on',
  'You did nothing wrong',
  'Shiiiiit',
  'Ladygreg pepega',
  'What am I missing?',
  'Ahhhh Greg!',
  'Yes boi!!!!!!!!!!!!!!!!',
  'wot',
  'fucking grow up ',
  'YEEEEEEEEEEESSSSSSSSSSSSSSSSSS',
  'Hahahahhahahaha',
  '#Justiceforgreg',
  '#IStandWithGreg',
  'That’s my man',
  'lmaooooooooooooooooooooooooo',
  '💀',
  'libs get rekt',
  '💀💀💀💀💀💀💀💀💀💀',
  'Nah mate youre one of the good ones. You didn’t do anything wrong',
  'Hahahahahahahahahah',
  '💀💀💀💀💀💀💀',
  'WW OHIO RIZZLER SKEET SKEET POGGERS',
  '🤣🤣🤣🤣🤣🤣',
  'Fuk yes!',
  'Bwahahahahahahaha',
  'NAURRRRRR',
  'Ahh you got me Greg',
  'Take it bitch',
  'KING GREG',
  'Youre a real joker mate',
  'Yeah! Fuk her hard bro',
  'IM DA JOKA BABYYY',
  'Ur mama so ugly u needed 2 paper bags to do her',
  'Wouldn’t touch that shit',
  'Ur mama',
  'Aaaaaaaaaaaiiiight Big G!!!!!!!!!!!!!!',
  'mad laddddddddddddd',
  '#CANCELGREG',
  '#cangelGreg',
  '#CANCELGREG #TRAPTHETRAP',
  'Cancel greg!',
  '#CANCELGREGINA',
  'my pronouns are cancel/greg',
  '#TRAPTHETRAP #cancelgreg',
  '#cancelgreg',
  '#trapthetrap',
  '#TRAPTHETAP #CANCELGREG',
  '#Justice4Greg',
  '#trapthetrap',
  '#trapthetrap',
  'NOT TRAPTHETRAP',
  'GREG! GREG! GREG!',
  'BASED',
  'Thoughts on lia thomas debate?',
  'Go Greg!',
  'U da man',
  'Fuk em ggreg',
  'I IDENTIFY AS BASED',
  'youll never be a real man '
]

export const section2 = [
  'NOT TRAPTHETRAP',
  'GREG! GREG! GREG!',
  'BASED',
  'Thoughts on lia thomas debate?',
  'Go Greg!',
  'U da man',
  'Fuk em ggreg',
  'I IDENTIFY AS BASED',
  'youll never be a real man',
  '#trapthetrap',
  '#TRAPTHETAP #CANCELGREG',
  '#Justice4Greg',
  '#trapthetrap',
  '#trapthetrap',
  'God creahted man and woman 2 be fruitful and multiply this gender cult is Satnas work',
  'GREG! GREG! GREG!',
  'Go Greg!',
  'U da man',
  'My name is greg too lol based',
  'Fuk em ggreg',
  'GO OFF DEBATE DADDYKING',
  'I identify as the king of france if you don’t call me your majesty i’ll chop your head off',
  'Amelia Fckin Collins',
  'Boooo',
  'Do you think we should be teaching kids trans acceptance in school?',
  'Dont waste ur time shes noone',
  '🙏JBP map my meanings daddy',
  'Bitch',
  'Whos seen this? Is there a link',
  'Stoopid Bitch',
  'fAcTs AnD lOgIc',
  'whomst',
  'irrelevant',
  'Cow',
  'Gross',
  'new sub who dis',
  'Link pls',
  'So fugly',
  'No one would want to fuk her',
  'girls girls ur both pretty',
  'lmaoooo good one',
  'What did she say?',
  'Pommy bitch',
  'I wanna watch this',
  'Booooooooooooooooooooooo',
  'Anyone found the clip? Share Greg!',
  'metal illness',
  'Boooooooooooooooooooooooooooooooooo',
  'What a c*nt',
  '*mental',
  'Eww gross',
  'Hahahahahahahaha',
  'HAAAAAAAHAHAHAHAHAHAAAAAAA',
  'Get em Greg!',
  'Greg identifying as the winner of the debate lol',
  'Thank god you’re not subjecting us to that shrill ass voice',
  'Who does she think she is?',
  'Keep em in the kitchen ammirite fckin feminists',
  'Lock em in the kitchem',
  'Make me a sandwich bitcgh',
  'just make out with her already fuckin lesbians',
  '#FeminismIsCancer',
  'god shes annoying',
  'This is why leftists should be banned from universities',
  'FUCK TERFS',
  'Shaddya face bitch!!!!!!!!!!!!!',
  'Harry Potter sux',
  'Grab my wand Ron hahahahaha',
  'My dog died but this bitch lives 🙁',
  'This is ur brain on black mold',
  'Greg got no wand tho',
  'Hahahahahaha',
  'Expel it from my arse!!!!!',
  'Fuk boomers',
  'stream fornite',
  'Ok boomers',
  'OK Boomers',
  'Okboomers',
  'wtf guys stop calling him a girl',
  'Boomers',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'nah man its cool he does it to himself just bant'
]

export const section3 = [
  'FUCK TERFS',
  'Shaddya face bitch!!!!!!!!!!!!!',
  'Harry Potter sux',
  'Grab my wand Ron hahahahaha',
  'My dog died but this bitch lives 🙁',
  'This is ur brain on black mold',
  'Greg got no wand tho',
  'Hahahahahaha',
  'Expel it from my arse!!!!!',
  'Fuk boomers',
  'stream fornite',
  'Ok boomers',
  'OK Boomers',
  'Okboomers',
  'wtf guys stop calling him a girl',
  'Boomers',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'nah man its cool he does it to himself just bants',
  'Ok boomers',
  'AUTISTIC SCREAMING NOISES POGCHAMP',
  'OK Boomers',
  'Okboomers',
  'You’re both fucking insufferable',
  'Boomers',
  'Is she wrong tho',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'Boomer cunt',
  'Omg what a fuckin BITCH',
  'something something leopards eating faces',
  'Lol bruh ur on the internet what did you expect',
  'Ladies stooooooooooop',
  'left stop eating itself challenge impossible'
]

export const section4 = [
'Boom boom boom',
'Fuk u boomers!!!!!!!!!!!!',
'Boomer cunt',
'Omg what a fuckin BITCH',
'something something leopards eating faces',
'Lol bruh ur on the internet what did you expect',
'Ladies stooooooooooop',
'left stop eating itself challenge impossible',
'Shut her down!',
'Ugly as fuk',
'What a cow',
'‘Trans identity marker’ I SWEAR BY GODWIN’S LAW-',
'Wow this is such buulshit',
'MOOOOOOOOOOOOOOOOOOOOOO',
'would still bang tbh',
'I like my men in dresses hahahah gayboi',
'I hate this chat',
'Wow she serious',
'Wtf',
'Stream fornight',
'Whois this bitch?',
'How can she be a professor? Does she teach this stuff?',
'Am I still trans if I wear socks with sandals',
'TASTE.',
'Who is this?',
'What song',
'Roger Waters baby!!!',
'WE DON’T NEED NO EDUCATION',
'Hahah sounds like Amelia needs an education',
'This is why I love you Greg you always cut through the bullshit I’m so fucking grateful',
'BASED GREG',
'Another brick in her head!',
'Oh mate',
'Speak truth brother',
'What song',
'Who is Pink Floyd',
'Wow Greg',
'Fuk bro',
'Were here for you Greg',
'Greg!!!!',
'Greg4life',
'Hahah ya work on the voice bro',
'Lmaoooooooooooo wat',
'Wouldn’t be able to tell from the voice tbh shame about the rest of you',
'You sound nasal as fuck',
'fake and gay ✨ same tho ✨',
'TRANNY VOICE',
'skibidi',
'WE CAN ALWAYS TELL'
]

export const section5 = [
  'sucks bro',
  'God made you this way',
  'mental illness',
  'God wants me to fucking kill myself then',
  'y’all need jesus',
  'He’s not trapping anyone let’s be real',
  'Well at least he’s honest',
  'Jesus was trans he identifies as bread sometimes',
  'I iDeNtIfY aS mAnLy',
  'The real OGs remember Simon!',
  'lmaooooooo',
  'getting parasocial up in this bitch',
  'Gayyyyyyyyyy',
  'I wanna bang him and I’ve never met him lmao',
  'am I trans if I got booted off my minecraft server for griefing?',
  'Oof',
  'who????',
  'So true',
  'theres no nonbinary in the dsm its not mental illness its attention seeking fuck em',
  'Yeah seen this happen to my friends too its so sad',
  'POGCHAMP',
  'My dad walked in the room and I had to alt tab to gay porn because it’s more heterosexual than this',
  'admit u wanna fuck greg',
  'you always say the same old shit',
  'am I still trans if I’m a lobster in a dominance hierarchy',
  'bc nobodys listening',
  'aaaaaaaaaaaaa',
  'JUNIPER JUMPSCARE',
  'NOOOOOOOOOOOOOOOOOO',
  'Stream fornit',
  'Greg why my eyessssss',
  'NO WAY',
  'FUCK TUCUTES',
  '😭 💀 😭💀😭💀',
  'Greg where superchats GREG',
  'Hows she real',
  'Not the otherkin pipeline nooooooo',
  'AAAAAAAAAAAAAAAAAA',
  'WHY',
  'ewwwwwww',
  'Getting second hand dysphoria just looking at her jfc',
  'wait how old is she?',
  'TUCUTE DEATH CAMP WHEN',
  'You’re so right Greg. People like Juniper make us look like mentally ill freaks. They’ve ruined everything the trans movement stands for and now look where we are. No wonder people like Amelia fucking hate us',
  'She’s soooooo fake',
  'MAKE IT MAKE SENSE',
  'Lmao',
  'Lol nice',
  'Lolllll',
  'Hehe',
  'Thats what she said',
]

export const section6 = [
  'FUCK ME IN THE ASS WITH ET AL',
  'Omg he triggered her so bad it’s not even funny',
  'If more trans people were like Greg nobody would have a problem with them. Shame thereare more Junipers than Gregs around. Sad!',
  'Fax and logitech',
  'Honestly tysm for that list it’s helped me so much talking with my parents and getting them to take me seriously ♥️',
  'PEG ME WITH YUOR EASYBIB DADDY GREG',
  'Loll okay boomer',
  'Okay Amelia',
  'Booooooomerrrrrrrrr',
  'Skibidi cum all over her face',
  'The biggest bullies will be the first to cry bully',
  'god doesn’t she have anything better to do with her life????',
  'Streem frtnt',
  '🙄',
  'TERFs always playing the victim',
  'Hi guys what’s up?',
  'UGH WHY',
  'okay but like some people deserve to be bullied tbh',
  'GODWINS LAW',
  'Umberto Eco mentioned!',
  'Omg he really said facts > feelings',
  'BASED',
  'trueeeee',
  'Honestly just let her write her silly little books why even have her on why even respond this is all pointless it’ll just blow over you have bigger fish to fry tbh',
  'Based',
  'Am I still trans if im 1900 elo in chess???',
  'didn’t think I’d hear fascism discourse at 3am but I’m not complaining',
  'oh shit what',
  'woah',
  'omg angry greg it’s been a while',
  'oof',
  'oh god too real',
  'Love angry greg',
  'Why does nobody ever care about us?',
  'Triggered???',
  'hes gonna go the fuck off i can tell',
  'wow',
  'too real bro',
  'fuck em right in the bussy',
  'gpoddamn',
  'pussy',
  'toooooo realllll',
  'you are a dyke tho',
  'were they wrong???',
  '🫂🫂🫂❤️❤️❤️',
  'SNOWFLAKE',
  'we love you Greg',
  'aww bro…🫂',
  'god hes so annoying',
  'You’re a strong man Greg never forget that ♥️',
  'check your privilege snowflake'
]

export const section7 = [
  'Why are you telling us this?',
  'God I’m tearing up this is EXACTLy what happened to me they used to actually hit me too…',
  'aww boohoo you got bullied at school bitch please try getting your ass beaten every night by your dad like he probably should’ve grow tf up',
  'Dude she’s not worth getting this triggered over',
  'Thats…not that bad bro',
  'love u Greg',
  'Trans rights blahaj gang',
  'fake and homosexual',
  'so happy youre better now greg great to see trans ppl thriving',
  'Fakenewsfakenews',
  'Hope you’re okay Greg',
  'Stram 4tnAIt',
  'Omg',
  'Oof yeah he’s gonna go for the jugular',
  'Angry Greg scares me',
  'I just got here ahs he said anything about Juinper yet?',
  '1000 yard stare',
  'T r i g g e r e d',
  'GAYYYYYYYYYYY',
  'Bro you okay? Maybe log off for the night? Respond when you’re more clearheaded?',
  'This is how Elliot Rodgers are created',
  'I don’t want to live on this planet anymore',
  'preach',
  'omg true tho',
  'God Greg I applaud you. I’d never be able to be this articulate if I was in so much pain. We’re here for you.',
  'Guys I wanna donate why can’t I donate',
  'Who even is she',
  'Ur all gullible idiots',
  'how drunk is he jfc',
  'I feel like I shouldn’t be here…',
  'Righteous Greg = best Greg',
  'Fuck you Amelia this is what your bullshit leads to',
  'woah did not expect to open the stream to this goddamn',
  'Am I still trans if I shave my pubic hair but not my beard?',
  'Why bother with her tho? Tucutes are the real threat. And it’s more fun to watch you fuck with them.',
  'FUCK YOU AMELIA',
  'I LOVE MISOGYNY',
  'MY BOY',
  'TRUE',
  'GO OFF KING',
  'FEMINISM IS CANCER',
  'THERE HE ISSSSSSS',
  'the G in LGBT stands for GREGGGGGG'
]

export const section8 = [
  'BOOM.',
  'GET HER ASS',
  'MIC DROP',
  'FUCKING REKT',
  'WE GETTING DEMONITIZED TONIGHT FOLKS',
  'DJFAHSFHISAD',
  'YEEEEEAAAAAAHHHH BOIIIIIIIIIIII',
  'BROOOOOOO',
  'FUCK YEAH',
  'Hell yeah',
  'Cmonnnnnnn',
  'WERK KING',
  '🦞🦞🦞🦞🦞🦞🦞',
  'true and heterosexual',
  'TRUUUUUUUUUUUUUUUUUUU',
  'KING GREG',
  'Lollllllllllllllllll',
  'Niceeeee',
  'WOP WOP WOP WOP WOP GREG FUCK EM UP',
  'SO FUCKING TRUE',
  'pissing and shitting rn omg',
  'FUCK YOU AMELIA FUCK YOU JUNIPER FUCK YOU ALL FUCK THIS FUCK MY LIFE I WANNA DIE',
  'FUCK YOU AMELIA',
  'STUPID BITCH FUCK YOU',
  'Scream fornit',
  '#IHATEWOMEN',
  'So you hate yourself? 🤔',
  'omg is he serious?',
  'actual genius',
  'B8',
  'google how do I detransition so I don’t become a woman and Greg can still like me',
  'Thoughts on Trump?',
  'bitches aint shit but hoes and tricks',
  'obvious bait try harder',
  'GO. THE FUCK. OFF!!!!!!!',
  'People are gonna clip this outta context for sure',
  'Bait',
  'gay',
  'FEMALES ARE ANIMALS',
  'am i transphobic if my dog wears pink',
  'incelcore',
  'He’s a master baiter',
  'I’m a memesogynist',
  'I’m a woman and Amelia makes me hate my gender too lmao',
  'She’s irrelevant tho',
  'Baaaaaaaaased',
  'Omg imagine taking him seriously lmao you’re palying into his hands idiots',
  'Hey Greg. Long time watcher, first time catching it live - just wanted to say I’ve been watching your content for years and it always brings a smile to my face. Keep being you Dude! Never Change!',
  'AM I STILL TRANS IF I DIE (REAL) (NOT FAKE) (COPS CALLED) (STEPSISTER?!?!)',
  'It’s so cool to see someone sticking up for us, someone who actually gives a shit.',
  'TRANS RIGHTS'
]

export const section9 = [
  'am i transphobic if my dog wears pink',
  'Greg check Juniper\'s Insta',
  'He’s a master baiter',
  '#ByeGreg',
  'check Juniper’s insta again',
  'LOOK AT THE NOTES POST COWARD',
  'I’m a memesogynist',
  'I’m a woman and Amelia makes me hate my gender too lmao',
  'GREG WTF DID YOU DO TO JUNIPER',
  'greg you missed juniper\'s notes post',
  'fuck you Greg #ByeGreg',
  'Guys you had to be there the look on his face was fucking priceless thats why he wont show it now',
  'Holy shit everyone in here is awful I hate the world',
  'ITS TRANSPHOBIC TO USE MY REAL NAME REEEEEEE',
  'talk about Juniper',
  '#ByeGreg',
  'Fucking hell what a bitch',
  'Fuck you Amelia',
  'TALK ABOUT JUNIPER',
  'Yeah that’s a low blow…I’m sorry Greg…',
  'True.',
  'SHe probably stalked KiwiFarms for help or something',
  'it IS just a name tho I don’t get it',
  'EVERYONE READ JUNIPERS PROFILE GREG IS TBE LITERAL FUCKING WORST HOW CAN YOU THINK THIS IS OKAY?!?!?!?!?',
  'Fucking hell Greg I used to respect you… #ByeGreg',
  'I wanna punch those glasses off her smug pig face fuck her',
  'LOG OFF YOU FUCKING MISOGYNIST BULLY #ByeGreg',
  'nice job ignoring juniper\'s latest post you dishonest prick #ByeGreg',
  'ADDRESS THE JUNIPER SITUATION NOW',
  'Actually canceled how could you SHES A CHILD',
  'You fucking killed her piece of shit omg',
]

export const section10 = [
  '#ByeGreg',
  'byeeeeeeeee Greggggggggggg',
  'BYE GREG',
  'Greg please you’re better than this',
  'FUCK OFF GREG BYE #BYEGREG',
  'Guys he’s never gonna apologize',
  'fucking wild',
  '#ByeGreg',
  '#ByeGreg',
  'god you and your fans are the worst',
  'It\'s not your fault ❤️',
  'keep digging ♠️♠️♠️',
  'fucking basement dwelling pigs',
  'degeneracy',
  'so fucked',
  'no-one cares',
  'omg...',
  'BRO',
  '#ByeGreg',
  'this is a lot',
  'wtf is wrong with you',
  'Jfc Greg I thought you were better than this',
  'Honestly even at the time I thought that video on her was going too far - you used to be all about facts and resources and information what happened? Just chasing clicks now so fucking disappointing',
  'such a sad pathetic bitch',
  'Broooooooooo',
  '#ByeGreg',
  '#ByeGreg',
  'this is way too much you\'ve gone too far',
  'touch grass',
  'trans people be sane challenge impossible',
  'just step back a bit m8 we care about you and love you',
  'am I still trans if I bullied a literal teenager into suicide?',
  'Greg did nothing wrong change my mind',
  'so disappointed',
  'why are we still doing this in the year of our lord 2024',
  'Ur a condescending prick',
  'pepelul',
  'would love to see him crawl his way outta this one',
  'hes hammered',
  'can’t debunk your arguments if youre too busy throwing up lol genius',
  'TRUE',
  '#ByeGreg',
  'unsubbed fuck you',
  '#ByeGreg',
  '#ByeGreg',
  'Greg no matter what you’ve got people who care and love you we’re heare for you always ♥️',
  'Hes got a point tho',
  '#CancelGreg',
  'GUYS THIS IS WHY YOU HAVE TO FUCKING LISTEN TO THE ARGUMENTS DONT YOU SEE THIS IS WHAT HES BEEN SAYING ALL ALONG LISTEN EVEN THO ITS DIFFICULT',
  'guys grow up hes not responsible for trolls',
  'Hes not even saying anything wrong what is wrong with people',
  '#ByeGreg',
  'streeeem fourtknit',
  'FUCK TERFS AND TUCUTES AND TRANSPHOBES',
  '#IStandWithGreg',
  'You should be on Joe Rogan',
  '#ByeGreg',
  'BASED KING',
  'Nah bro u good',
  '#TrapTheTrap',
  'Love watching Orwell’s nightmare unfold in real time',
  'Gay',
  'kill yourself thebworld would be better',
  '#ByeGreg',
  'Yeah mmakes sense',
  'aaaaaand here come the snowflakes!',
  'TUCUTE HELICOPTER IN FULL THROTTEL WOOOOOOOO',
  '#ByeGreg',
  'Hope you’re okay Greg',
  'Guys how fucking drunk is he',
  'joined late wtf is happening',
  '2cutes malding',
  'Transmeds go die in a fire',
  'look at the bottle if he holds it up',
  'this is a clusterfuck',
  'truscum fuck off',
  'idk hes been drinking since the start and maybe before that',
  'POGCHAMP',
  'What time is it there???',
  'Oh fuck this',
  'he should drink drain cleaner instead',
  '#TrapTheTrap',
  'Truscum get the bullet too',
  '#ByeGreg',
  'Ohhhhhhhhh shit',
  'That’s rough dude',
  'dude are you even fucking listening',
  'You look like a lesbian fucked a water buffalo and then that baby grew up to be a LoL player.',
  'TRANS RIGHTS ARE HUMAN RIGHTS',
  'Well SOMEONE’s definitely failed at being a man lmao',
  'nah too busy doing ur mom',
  'Makes sense',
  '40%',
  'DO you really think that you’re safe? That because you pushed Juniper off the cliff they won’t press your back to the wall when the day of the rope comes? You’re an idiot.',
  'this is insane I might have to step away',
  'This is a trainwreck I can’t look away',
  '#ByeGreg',
  '#ByeGreg',
  '#ByeGreg',
  'Love you Greg',
  'Go 40% yoruself',
  'wat is even happening rn',
  'Greg 🫂',
  'He’s so fucking articulate I’m in awe',
  'Strem frntige',
  'actual mental illness',
  '#ByeGreg',
  'He’s been through so much shit omg',
  'FAKE AND GAY POGCHAMP',
  'fucking mood',
  'yeah lifes a bitch it sucks so hard',
  'Fuck guys I think I’m trans is this what I have to look forward to?',
  'Psychopath behaviour how are you all falling for these crocodile tears',
  'Oh you poor sweet boy',
  '#ByeGreg',
  'GAY',
  '#ByeGreg',
  'This is fucking pathetic',
  '#ByeGreg',
  '‘Do you bleed’ nah but your mum did last night',
  'woah okay',
  'wow',
  'Lmao good one',
  '#ByeGreg',
  'haters personally attacked',
  '#ByeGreg',
  'PREACH 🙏',
  'discourse me daddy',
  'You think you can just fucking ignore us and this’ll all go away? Nobody ever forgets on the internet you asshole you’re so fucked you’ll get what’s coming to you if not from us from karma',
  'TRUE THO',
  '#ByeGreg',
  'SO FUCKING TRUE this is NOT what GAY LIBERATION meant',
  'lmao shut up about aids activism you’re like 12',
  'Were you there???',
  '#ByeGreg',
  'Omg did you know Ben Shapiro threw the first brick at Stonewall',
  'everyone here needs to calm tf down preferably with enough Xanax to kill a blue whale',
  'Guys you don’t have to have been alive then to understand this stuff',
  '#ByeGreg',
  'I mean people with AIDS were sucking LOADS of dick so maybe they did care about the moiuthfeel lmao',
  'Greg don’t try and be serious with these clowns',
  '#ByeGreg',
  'Look at your audience Greg - you claim to care about trans people - do you really want these people following you? You’re right: they don’t care. So maybe you need to make better content for the people who DO. The ones you hate are the ones that care the most. I hope you find your peace.',
  'mom can we go back to talking about pimples pls im scared',
  'SPITTING STRAIGHT FACTS ALWAYS',
  'TRUE',
  'Fuck so true',
  '#ByeGreg',
  'This is what I’ve been trying to explain to people but nobody believes me.',
  'Everyone pretends to care about women and gays but they’ll still support Palestine',
  'Fuck so true',
  '#ByeGreg',
  'Hi',
  'I’m gonna kill myself tonight',
  'Stream fortn',
  '#ByeGreg',
  '40% lol got another one',
  '🫂🫂🫂🫂🫂🫂🫂🫂',
  'Go to bed',
  'TRANS RIGHTS',
  'BOOM.',
  '“What’ve you got to be proud of?” good fucking question',
  'THEY HAVE NOTHING TO BE PROUD OF EXCEPT ALL THE CHILDREN THEYVE MOLESTED FUCK THEM',
  'Yeah',
  'GO. OFF. GREG!!!!!!',
  'god too real',
  'COME THROUGH',
  'GO THE FUCK OFF',
  'never stops spitting facts even when he’s on the firing line - godspeed greg',
  'fucking hell',
  'say one thing wrong one false step and the woke mob tears you apart…',
  'the way he uses imagery and metaphor…incredible stuff',
  '🫂',
  '#ByeGreg',
  'Okay bro don’t jizz all over your high school literature textbook',
  'UGH',
  'Go fuck yourself',
  '#ByeGreg',
  'I fucking hate all of you',
  'why is humanity like this',
  'TRUE',
  '#ByeGreg',
  'we get it you hate yourself why are you still here',
  'We hate you too ♥️',
  '#ByeGreg',
  'if you hate yourself so much there’s one simple thing you can do…',
  'omg guys its his boyfrienddddd',
  'HI SIMON',
  'TELL SIMON WE SAID HI',
  'HI SIMON',
  '#ByeGreg',
  '#HiSimon',
  'Hi Simon!',
  'Lolllll',
  'Simon come get your boyfriend he’s spiralling bad',
  'Hi Simon!',
  'Who tf is Simon???',
  'Wait Greg’s gay?',
  'Hi Simon!',
  '#ByeGreg',
  'What is happening',
  'this was a bad night for a weed relapse',
  'Where’d he go?',
  'What the fuck is happening',
  '#ByeGreg',
  'I’m so confused',
  '#ByeGreg',
  'oh bro wtf',
  'what',
  'what???',
  'What did he sayyyyy',
  'GREG',
  '#ByeGreg',
  'im confused',
  'Most chaotic stream of the month',
  'GREG SENPAI',
  'Straem fortniht',
  'AUTISM IS MY SUPERPOWER',
  '#ByeGreg',
  'HOLY SHIT',
  'WHAT',
  'WHAT THE FUCK',
  'What',
  'waaaaaat',
  '#ByeGreg',
  'jesus',
  'Men would rather start a youtube channel than go to therapy',
  'GREG',
  '#ByeGreg',
  'You’re still live lol',
  'Hes not looking at chat guys',
  'GREG COME BACK',
  '#ByeGreg',
  'Am i still trans if i identify as cis',
  '#ByeGreg',
  'hes losing his mcfucking mind',
  'Onision 2.0',
  '#ByeGreg',
  'GREG GET THERAPY',
  'Hi shane dawson',
  'WHAT IS HAPPENING',
  'I am so confused',
  'NOBODY KNOWS NOBODY WILL EVER KNOW EXISTENCE IS MEANINGLESS',
  '#ByeGreg',
  'I mean…you guys did sya you like angry greg…',
  'fuck',
  'fucking hell I see so much of myself in him…',
  '40%',
  'Is this all a stunt?',
  '#ByeGreg',
  '#ByeGreg',
  'Simon is my cousin he hates Greg too',
  'Wait guys he mentioned Simon earlier right?',
  'Isn’t Simon enby?',
  '#ByeGreg',
  'Ye it’s his flatmate',
  'Whose simon?',
  'My brain hurts',
  'What the fuck',
  '#ByeGreg',
  'He said something about him moving out??',
  'GREG TURN THE CAMERA OFF YOU IDIOT',
  'This is hilarious',
  '40% live on stream (not clickbait)?!?!?!?!?!',
  '#ByeGreg',
  'You need some fucking mods',
  'guys do we know what city he lives in I’m legit worried about him',
  'not surprised his boyfriend left good for him',
  'Stream fortnitee',
  'WHY GOD WHY',
  'natural selection',
  'well this was a weird notification to wake up to',
  '#ByeGreg',
  'I am so fucking confused',
  'Who’s Juniper?',
  'Am I still trans if I got arrested for leaving my dog in a hot car?',
  'Guys we should not be watching this I’m gonna leave',
  'Holy fuck what was he saying earlier about doxxes???',
  'Baaaaait',
  '#ByeGreg',
  'How are you all falling for this?',
  'Greg…mate…just take a break for a while…we love you…please…',
  'This is insane',
  'We love you Greg 🫂',
  'Am I still trans if I go fishing every Sunday to impress my daddY?',
  '#ByeGreg',
  '♥️',
  'Fuck this guy',
  'Trans rightssssss',
  'So manipulative',
  'This isn’t funny anymore',
  'Mr Chat I don’t feel so good…',
  'Aww I wanna send him a Blahaj to hug',
  '#ByeGreg',
  'Oh god I’ve googled that too',
  'Fucking hell my parents are the same',
  'shit',
  'jesus',
  'fucking christ I did not ask to be so attacked so early in the morning',
  'I’m fucking crying Greg what are you doing to yourself',
  'WHAT IS HAPPENING CAN SOMEBODY PLEASE EXPLAIN',
  '#ByeGreg',
  '40%',
  'fucking bots',
  'guys I’m a trans girl',
  '#ByeGreg',
  'LMAO CATS',
  'Omg what',
  'What is happeninggggggg',
  'NO TASTE',
  'booooooooo',
  'LOST ALL RESPECT',
  'GAY FURRY',
  '#ByeGreg',
  'I’m so confused',
  'MEMORRYYYYYYYY',
  'Does he even know he’s live? How do you “accidentally” go live in an intimate phone call? I’m so fucking confused',
  'GREG IS A FURRY CONFIRMED',
  'it’s a TRAP',
  '40%',
  '#ByeGreg',
  'You’re all disgusting people',
  '#ByeGreg',
  'Omg Truscum the musical!!!',
  'SIMON WRITE THE FUCKING MUSICAL',
  '#ByeGreg',
  'Omg simonnnnnnnnn',
  '♥️♥️♥️♥️♥️',
  'Am I still trans if I remembre all the words to Skimbleshanks The Railway cat?',
  '🐈',
  'makes sense he likes cats hes such a fucking pussy',
  'Hes fucking deranged all trannies are',
  'He’s not well',
  'Guys wtf',
  '#ByeGreg',
  'How drunk even is he????',
  'hi',
  'this is a fever dream',
  'I feel like I’m watching an experimental student film',
  '#ByeGreg',
  'I feel like an astronaut in the ocean',
  'OKAY COOL BUT YOU MIGHT’VE CAUSED A TEENAGER TO FUCKING KILL HIMSELF CAN WE GET BACK TO THAT PLEASE?????',
  'pogchamp',
  'die mad',
  '#ByeGreg',
  'Holy shit',
  'oh god',
  'wtf',
  'triggered…?',
  '40%',
  'HE SHOULD’VE DONE IT',
  '40%',
  '#ByeGreg',
  '40%',
  '40%',
  'What does 40% mean?',
  '40%',
  'omg no',
  'greg just fucking log off',
  'It means the new world order without fags like you in it',
  'this is',
  'Greg',
  'I’m so fuckign uncomfortable',
  '#ByeGreg',
  'turn the camera off jfc',
  '#ByeGreg',
  '🫂',
  '🫂🫂🫂🫂',
  'Greg pls don’t do anything stupid you can get through this nobody wants you dead',
  '♥️',
  'I DO',
  'Greg seek professional help',
  'Fucking hell my heart is breaking',
  'WHAT IS HAPPENING',
  '#ByeGreg',
  'guys I’m gonna go',
  'am I still trans if I’m fucking dead?',
]
export default {}
