export const section1 = [
  'Hi Greg',
  'Hello',
  'Hi Greg',
  'Hey Greg',
  'Greg!',
  'Hi all',
  'Hihi',
  'Greggles!',
  'Yo G!',
  'Hey Greg',
  'Hi Greg',
  'Sup bro',
  'GREG!!!!!',
  'Hi',
  'Hi',
  'ITSGREGG!!!!!!!',
  'Hey',
  'Sup',
  'Hi all',
  'Greg the Man!',
  'What is this shit?',
  'Hi all',
  'Greg!',
  '???',
  'Sorry? For what?',
  'Hi Greg',
  'What’s going on?',
  'Wachu talkin bout',
  '?',
  'Hi all',
  'Woah what did I miss?',
  'Hi Greg',
  'Huh?',
  '?',
  'Pussy',
  'Wha',
  'Fuk dis',
  'Hi all',
  'Grow a pair hahahahaha',
  'Fml',
  'Eww don’t fkn cry or shit',
  'You have nothing to apologise for! Speak your truth!',
  'Whats going on',
  'You did nothing wrong',
  'Shiiiiit',
  'Ahhhh Greg!',
  'Yes boi!!!!!!!!!!!!!!!!',
  'YEEEEEEEEEEESSSSSSSSSSSSSSSSSS',
  'Hahahahhahahaha',
  '#Justiceforgreg',
  'That’s my man',
  'Nah mate youre one of the good ones. You didn’t do anything wrong',
  'Hahahahahahahahahah',
  'Fuk yes!',
  'Bwahahahahahahaha',
  'Ahh you got me Greg',
  'Take it bitch',
  'Youre a real joker mate',
  'Yeah! Fuk her hard bro',
  'Ur mama so ugly u needed 2 paper bags to do her',
  'Wouldn’t touch that shit',
  'Ur mama',
  'Aaaaaaaaaaaiiiight Big G!!!!!!!!!!!!!!',
  '#CANCELGREG',
  '#cangelGreg',
  '#CANCELGREG #TRAPTHETRAP',
  'Cancel greg!',
  '#TRAPTHETRAP #cancelgreg',
  '#cancelgreg',
  '#trapthetrap',
  '#TRAPTHETAP #CANCELGREG',
  'GREG! GREG! GREG!',
  'Go Greg!',
  'U da man',
  'Fuk em ggreg',
]

export const section2 = [
  '#trapthetrap',
  '#TRAPTHETAP #CANCELGREG',
  'GREG! GREG! GREG!',
  'Go Greg!',
  'U da man',
  'Fuk em ggreg',
  'Amelia Fckin Collins',
  'Boooo',
  'Bitch',
  'Whos seen this? Is there a link',
  'Stoopid Bitch',
  'Cow',
  'Gross',
  'Link pls',
  'So fugly',
  'No one would want to fuk her',
  'What did she say?',
  'Pommy bitch',
  'I wanna watch this',
  'Booooooooooooooooooooooo',
  'Anyone found the clip? Share Greg!',
  'Boooooooooooooooooooooooooooooooooo',
  'What a c*nt',
  'Eww gross',
  'Hahahahahahahaha',
  'HAAAAAAAHAHAHAHAHAHAAAAAAA',
  'Get em Greg!',
  'Keep em in the kitchen ammirite fckin TERFs',
  'Lock em in the kitchem',
  'Make me a sandwich bitcgh',
  'FUCK TERFS',
  'Shaddya face bitch!!!!!!!!!!!!!',
  'Harry Potter sux',
  'Grab my wand Ron hahahahaha',
  'Hahahahahaha',
  'Expel it from my arse!!!!!',
  'Fuk boomers',
  'Ok boomers',
  'OK Boomers',
  'Okboomers',
  'Boomers',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!'
]

export const section3 = [
  'Ok boomers',
  'OK Boomers',
  'Okboomers',
  'Boomers',
  'Boom boom boom',
  'Fuk u boomers!!!!!!!!!!!!',
  'Boomer cunt',
  'Omg what a fuckin BITCH',
  'Transphobic bitch'
]

export const section4 = [
  'Shut her down!',
  'Ugly as fuk',
  'What a cow',
  'Wow this is such buulshit',
  'MOOOOOOOOOOOOOOOOOOOOOO',
  'I like my men in dresses hahahah gayboi',
  'Wow she serious',
  'Wtf',
  'Whois this bitch?',
  'How can she be a professor? Does she teach this stuff?',
  'Hahaha Pink Floyd yes!!!',
  'We don’t need no education',
  'Nother brick in da waaaaaaaaall',
  'Who is this?',
  'What song',
  'Roger Waters baby!!!',
  'We don’t need no education',
  'Hahah sounds like Amelia needs an education',
  'Another brick in her head!',
  'Oh mate',
  'Speak truth brother',
  'What song',
  'Who is Pink Floyd',
  'Wow Greg',
  'Fuk bro',
  'Were here for you Greg',
  'Greg!!!!',
  'Greg4life',
  'Hahah ya work on the voice bro'
]

export default {}
